name: cdk

on:
  push:
    branches:
      - master
  pull_request:

env:
  AWS_REGION: 'ap-northeast-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  aws_cdk:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup dependencies
        run: yarn install

      - name: Unit tests
        run: yarn test

      - name: Show diff
        run: yarn diff

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: yarn deploy
